# Assignment 1

This notebook contains the code for Assignment 1.

# Task 1: A list of dictionaries

In [4]:

transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

# Quick check
print(transactions)

[{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU'}, {'id': 2, 'product': 'Phone', 'price': 800, 'quantity': -1, 'region': 'US'}, {'id': 3, 'product': 'Tablet', 'price': 0, 'quantity': 5, 'region': 'EU'}, {'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US'}, {'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU'}, {'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC'}]


### a) Filter invalid transactions

In [6]:


valid_transactions = []

for transaction in transactions:
    # Keep only valid ones
    if transaction["price"] > 0 and transaction["quantity"] > 0:
        valid_transactions.append(transaction)

# Check result
print(valid_transactions)

[{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU'}, {'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US'}, {'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU'}, {'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC'}]


### b) Compute Total per transaction

In [4]:
# Add total = price * quantity to each valid transaction

for transaction in valid_transactions:
  transaction["total"] = transaction["price"] * transaction["quantity"]

# Check result
print(valid_transactions)

[{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU', 'total': 2400}, {'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US', 'total': 1050}, {'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU', 'total': 1200}, {'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC', 'total': 750}]


### c) Group valid transactions by region and compute total revenue

In [5]:
# Create a dictonary to store total revenue per region
revenue_by_region = {}


In [6]:
# Loop through transactions and sum totals by region

for transaction in valid_transactions:
  region = transaction["region"]
  total = transaction["total"]

  # If region is not yet in dictionary, initialize it
  if region not in revenue_by_region:
    revenue_by_region[region] = 0

  # Add total to region
  revenue_by_region[region] += total

# Check result
print(revenue_by_region)

{'EU': 3600, 'US': 1050, 'APAC': 750}


### d) Print the region with the highest total revenue and its value using an f-string.

In [7]:
# Find the region with the highest revenue

max_region = None
max_revenue = 0

for region, revenue in revenue_by_region.items():
  if revenue > max_revenue:
    max_revenue = revenue
    max_region = region

# Check result
print("Region with highest revenue:", max_region)
print("Revenue:", max_revenue)

Region with highest revenue: EU
Revenue: 3600


# Task 2: Creating a function

In [8]:
# List of daily sales
sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

print(sales)

[1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]


### creating a function that summarizes sales

In [22]:
def summarize_sales(sales_list):
  # Total sales
  total = sum(sales_list)

  # Average sales (rounded to two decimals)
  average = round(total / len(sales_list), 2)

  # Best day (starting from 1)
  best_day = sales_list.index(max(sales_list)) + 1

  # Worst day (starting from 1)
  worst_day = sales_list.index(min(sales_list)) + 1

  # Days above average sales
  above_average_count = 0
  for value in sales_list:
    if value > average:
      above_average_count += 1


  return {
      "total": total,
      "average": average,
      "best_day": best_day,
      "worst_day": worst_day,
      "above_average_count": above_average_count
  }

In [23]:
result = summarize_sales(sales)
print(result)

{'total': 20510, 'average': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}


# Task 3: Loops

In [38]:
# List of student records
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

print(students)

[{'name': 'Anna', 'grade': 85, 'attendance': 0.92}, {'name': 'Erik', 'grade': 58, 'attendance': 0.75}, {'name': 'Mia', 'grade': 91, 'attendance': 0.98}, {'name': 'Leo', 'grade': 44, 'attendance': 0.6}, {'name': 'Sara', 'grade': 72, 'attendance': 0.88}, {'name': 'Tom', 'grade': 67, 'attendance': 0.7}, {'name': 'Nina', 'grade': 95, 'attendance': 0.99}, {'name': 'Olli', 'grade': 50, 'attendance': 0.65}]


### a) Create a new list called passing that contains only the names of students with a grade of 50 or above. Print the list.

In [39]:
# Create a list of a passing students

passing = []

for student in students:
  if student["grade"] >= 50:
    passing.append(student["name"])

print(passing)

['Anna', 'Erik', 'Mia', 'Sara', 'Tom', 'Nina', 'Olli']


### b) Loop through the students and print a status message for each. If the student's grade is 80 or above, print "[name]: Excellent"; if between 50 and 79, print "[name]: Pass"; otherwise print "[name]: Fail".

In [43]:
# Loop through the students and print status message

for student in students:
  name = student["name"]
  grade = student["grade"]

  if grade >= 80:
    print(f"{name}: Excellent")
  elif grade >= 50:
    print(f"{name}: Pass")
  else:
    print(f"{name}: Fail")

Anna: Excellent
Erik: Pass
Mia: Excellent
Leo: Fail
Sara: Pass
Tom: Pass
Nina: Excellent
Olli: Pass


### c) Count how many students have an attendance rate below 0.80. Print the count.

In [44]:
low_attendance_count = 0

for student in students:
  if student["attendance"] < 0.80:
    low_attendance_count += 1

print(low_attendance_count)



4


d) Find the student with the highest grade using a loop (do not use max()). Print the student's name and grade.

In [45]:
top_student = None
highest_grade = 0

for student in students:
  if student["grade"] > highest_grade:
    highest_grade = student["grade"]
    top_student = student["name"]

print(f"Top_student: {top_student}, Grade: {highest_grade}")



Top_student: Nina, Grade: 95


e) Find the student with the highest grade using max(). Print the student's name and grade.

In [47]:
top_student = max(students, key=lambda student: student["grade"])

print(f"Top student: {top_student['name']}, Grade: {top_student['grade']}")

Top student: Nina, Grade: 95


# Task 4: Class and methods

In [86]:
# Design a class called Portfolio that represents an investment portfolio. The constructor is provided for you:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

# a)

    def add_asset(self, ticker, shares, price_per_share):
      # Add or update asset
      self.holdings[ticker] = {
          "shares": shares,
          "price_per_share": price_per_share
      }

# b)

    def total_value(self):
      total = 0

      for asset in self.holdings.values():
        shares = asset["shares"]
        price = asset["price_per_share"]
        total += shares * price

      return total

# c)

    def most_valuable(self):
      max_value = 0
      top_ticker = None

      for ticker, asset in self.holdings.items():
        value = asset["shares"] * asset["price_per_share"]

        if value > max_value:
          max_value = value
          top_ticker = ticker

      return top_ticker

# d)

    def __str__(self):
      num_assets = len(self.holdings)
      total = self.total_value()

      return f"Portfolio owner: {self.owner}, Assets: {num_assets}, Total value: {total}"

a) A method add_asset(ticker, shares, price_per_share) that adds a new asset or updates the number of shares if the ticker already exists (in which case the price should also be updated).

In [99]:
# Portfolio owned by Wilhelm containing the following assets:

portfolio = Portfolio("Wilhelm")

# Assets
portfolio.add_asset("AAPL", 10, 150)
portfolio.add_asset("GOOGL", 5, 350)
portfolio.add_asset("NVDA", 15, 160)



In [100]:
print(portfolio.holdings)

{'AAPL': {'shares': 10, 'price_per_share': 150}, 'GOOGL': {'shares': 5, 'price_per_share': 350}, 'NVDA': {'shares': 15, 'price_per_share': 160}}


b) A method total_value() that returns the total market value of the portfolio.

In [101]:
print(portfolio.total_value())

5650


c) A method most_valuable() that returns the ticker of the asset with the highest total value (shares × price).

In [102]:
print(portfolio.most_valuable())

NVDA


d) A __str__ method that returns a readable summary of the portfolio, including the owner's name, the number of assets, and the total value.

In [103]:
print(portfolio)

Portfolio owner: Wilhelm, Assets: 3, Total value: 5650


# Task 5: Importing a module

In [112]:
# Order dates

orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]

In [113]:
print(orders)

[('2025-01-15', 'Laptop'), ('2025-01-22', 'Phone'), ('2025-02-03', 'Laptop'), ('2025-02-14', 'Tablet'), ('2025-03-01', 'Phone'), ('2025-03-10', 'Phone'), ('2025-03-22', 'Laptop'), ('2025-04-05', 'Monitor')]


In [114]:
from datetime import datetime

In [116]:
# Converting date strings into datetime.date objects

dates = []

for order in orders:
  date_str = order[0]

  date_obj = datetime.strptime(date_str, "%Y-%m-%d").date()

  dates.append(date_obj)

  print(dates)

[datetime.date(2025, 1, 15)]
[datetime.date(2025, 1, 15), datetime.date(2025, 1, 22)]
[datetime.date(2025, 1, 15), datetime.date(2025, 1, 22), datetime.date(2025, 2, 3)]
[datetime.date(2025, 1, 15), datetime.date(2025, 1, 22), datetime.date(2025, 2, 3), datetime.date(2025, 2, 14)]
[datetime.date(2025, 1, 15), datetime.date(2025, 1, 22), datetime.date(2025, 2, 3), datetime.date(2025, 2, 14), datetime.date(2025, 3, 1)]
[datetime.date(2025, 1, 15), datetime.date(2025, 1, 22), datetime.date(2025, 2, 3), datetime.date(2025, 2, 14), datetime.date(2025, 3, 1), datetime.date(2025, 3, 10)]
[datetime.date(2025, 1, 15), datetime.date(2025, 1, 22), datetime.date(2025, 2, 3), datetime.date(2025, 2, 14), datetime.date(2025, 3, 1), datetime.date(2025, 3, 10), datetime.date(2025, 3, 22)]
[datetime.date(2025, 1, 15), datetime.date(2025, 1, 22), datetime.date(2025, 2, 3), datetime.date(2025, 2, 14), datetime.date(2025, 3, 1), datetime.date(2025, 3, 10), datetime.date(2025, 3, 22), datetime.date(2025, 4,

In [118]:
# Find the earliest and latest dates

earliest = min(dates)
latest = max(dates)

# Compute the difference
difference = (latest - earliest).days

# Result: Number of days between earliest and latest
print(f"Earliest date: {earliest}")
print(f"Latest date: {latest}")
print(f"Days between: {difference}")

Earliest date: 2025-01-15
Latest date: 2025-04-05
Days between: 80


# Task 6: Array Operations and Broadcasting

In [130]:
# Quarterly revenue (in TEUR)

import numpy as np

# Rows: years (2022, 2023, 2024), Columns: quarters (Q1, Q2, Q3, Q4)
revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]
    ])



### a) Compute and print the total annual revenue for each year (i.e., row sums). Use the axis parameter.

In [132]:
# Print the annual totals (row sums)

annual_totals = np.sum(revenue, axis=1)

print(annual_totals)

[ 880  950 1080]


### b) Compute the mean quarterly revenue across all years (i.e., column means).

In [134]:
# Mean quarerly revenue for each year (column means)

quarterly_means = np.mean(revenue, axis=0)

print(quarterly_means)

[226.66666667 260.         206.66666667 276.66666667]


### c) Using broadcasting, apply a growth adjustment to the 2024 row by multiplying it element-wise with the array [1.05, 1.03, 1.08, 1.02]. Print the adjusted values.

In [135]:
# Growth factors
growth = np.array([1.05, 1.03, 1.08, 1.02])

# Apply to 2024
adjusted_2024 = revenue[2] * growth

print(adjusted_2024)

[262.5 298.7 248.4 316.2]


### d) Use boolean indexing to find and print all quarterly revenue values that exceed 250 (thousands of euros).

In [137]:
# Find values that exceed 250 (TEUR)
high_values = revenue[revenue > 250]

print(high_values)

[260 270 290 310]


# Task 7: Pandas

In [142]:
import pandas as pd

data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}

# Create DataFrame
df = pd.DataFrame(data)

print(df)


  employee department  salary  years_exp  performance_score
0     Anna    Finance    4500          5                4.2
1     Erik  Marketing    4000          3                3.8
2      Mia    Finance    4800          7                4.5
3      Leo         IT    5200         10                4.0
4     Sara  Marketing    3900          2                3.5
5      Tom         IT    5100          8                4.9


### a) Add a new column salary_per_year_exp computed as salary / years_exp. Round to the nearest integer.

In [144]:
df["salary_per_year_exp"] = (df["salary"] / df["years_exp"]).round(0)

print(df)


  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2   
1     Erik  Marketing    4000          3                3.8   
2      Mia    Finance    4800          7                4.5   
3      Leo         IT    5200         10                4.0   
4     Sara  Marketing    3900          2                3.5   
5      Tom         IT    5100          8                4.9   

   salary_per_year_exp  
0                900.0  
1               1333.0  
2                686.0  
3                520.0  
4               1950.0  
5                638.0  


### b) Sort the DataFrame by performance_score in descending order and print the top 3 employees.

In [145]:
# Sort and select top 3 employees

top_3 = df.sort_values(by="performance_score", ascending=False).head(3)

print(top_3)

  employee department  salary  years_exp  performance_score  \
5      Tom         IT    5100          8                4.9   
2      Mia    Finance    4800          7                4.5   
0     Anna    Finance    4500          5                4.2   

   salary_per_year_exp  
5                638.0  
2                686.0  
0                900.0  


### c) Using .loc, select all employees in the Finance department with a performance score above 4.0. Print the result.

In [146]:
filtered = df.loc[
    (df["department"] == "Finance") & (df["performance_score"] > 4.0)
]

print(filtered)


  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2   
2      Mia    Finance    4800          7                4.5   

   salary_per_year_exp  
0                900.0  
2                686.0  


### d) Rename the column years_exp to experience_years using the .rename() method.

In [147]:
# Rename column

df = df.rename(columns={"years_exp": "experience_years"})

print(df.columns)

Index(['employee', 'department', 'salary', 'experience_years',
       'performance_score', 'salary_per_year_exp'],
      dtype='object')


### e) Using .iloc, select and print the salary and performance score columns for the first four employees.

In [148]:
# select the first four employees and their salary and performance score

result = df.iloc[0:4][["salary", "performance_score"]]

print(result)


   salary  performance_score
0    4500                4.2
1    4000                3.8
2    4800                4.5
3    5200                4.0


# Task 8: More Pandas

In [149]:
# Script of daily website traffic

import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

### a) Create a DataFrame with columns: date, visitors, conversion_rate, and avg_order_value. Set date as the index.

In [152]:
# Create new DataFrame
df_traffic = pd.DataFrame({
    "date": days,
    "visitors": visitors,
    "conversion_rate": conversion_rate,
    "avg_order_value": avg_order_value
})

# setting "date" as index
df_traffic = df_traffic.set_index("date")

print(df_traffic.head())

            visitors  conversion_rate  avg_order_value
date                                                  
2025-01-06       206           0.0645            64.30
2025-01-07       472           0.0578            48.44
2025-01-08       437           0.0756            43.26
2025-01-09       221           0.0339            43.61
2025-01-10       563           0.0679            49.39


### b) Compute two new columns: conversions (= visitors × conversion_rate, rounded to the nearest integer) and daily_revenue (= conversions × avg_order_value).



In [155]:
# Compute conversions (rounded to the nearest integer)
df_traffic["conversions"] = (df_traffic["visitors"] * df_traffic["conversion_rate"]).round(0)

# Compute daily_revenue
df_traffic["daily_revenue"] = df_traffic["conversions"] * df_traffic["avg_order_value"]

print(df_traffic.head())


            visitors  conversion_rate  avg_order_value  conversions  \
date                                                                  
2025-01-06       206           0.0645            64.30         13.0   
2025-01-07       472           0.0578            48.44         27.0   
2025-01-08       437           0.0756            43.26         33.0   
2025-01-09       221           0.0339            43.61          7.0   
2025-01-10       563           0.0679            49.39         38.0   

            daily_revenue  
date                       
2025-01-06         835.90  
2025-01-07        1307.88  
2025-01-08        1427.58  
2025-01-09         305.27  
2025-01-10        1876.82  
